### PR TITLE
Ability to change the number of columns for github-picker

### PR DESCRIPTION
**Pull request by genekofman**
Added the ability to change the number of columns for github-picker or enable automatic calculation of the number of columns depending on the width of the component.

### CODE REVIEW

**Comment by pIvan** [comment]
Hi, @dintecom I have in plan to redesign color-presets component so for now,
this is on hold.
Thank You for your proposal.

**Review by pIvan — CHANGES_REQUESTED** [review]
Hi @ArtemDintecom,

in the lack of time, I have reviewd you're code, and the solution is fine,
please can you just add access modifiers to the getter, and please check method names there is a typo.

Kind regards,
Ivan

**Comment by ashikjs** [comment]
@pIvan Did you have anyplan to do this ? I am interest to work with this library.

**Comment by pIvan** [comment]
Hi @ashikjs, I have made changes just need to test them and push on github.
I'll do that this week

**Comment by ArtemDintecom** [comment]
Fixed remarks and added Coercing as in Angular CDK

**Comment by ashikjs** [comment]
> Hi @ashikjs, I have made changes just need to test them and push on github. I'll do that this week

Let me know if you have any channel or group, where all of those contributor can discourses like any discord group.

**Comment by pIvan** [comment]
Hi @ArtemDintecom I'll add a merge after office hours, 
I was currently pushed what I had prepared locally.

Thanks for help :)

**Comment by pIvan** [comment]
@ashikjs currently there is not any channel or group created for contributors

**Review by pIvan — APPROVED** [review]

**Pull request merged**
